### ISSUE TITLE
java.lang.NoClassDefFoundError: gherkin/formatter/Formatter

### ISSUE THREAD

**Issue by AmarnathN** [reportportal/agent-java-cucumber#9]
While Integration of Cucumber project to  Reportportal, I am facing the following Initialization exception

java.lang.NoClassDefFoundError: gherkin/formatter/Formatter
Caused by: java.lang.ClassNotFoundException: gherkin.formatter.Formatter

Please find my following runner class details
```

//@RunWith(CucumberWithSerenity.class)
@RunWith(Cucumber.class)
@CucumberOptions(
        //plugin = {"pretty", "html:target/cucumber-html-report"},
		plugin = {"pretty", "com.epam.reportportal.cucumber.StepReporter"},
	        `features` = "Artifacts\\TAF_2.6.1\\Features"
)
public class BusConfigRunner {

}
```

and the versions which i tried:

**agent-java-cucumber** : 2.6.1 and 3.0.0 and 3.0.1

with normal cucumber html plugin I am able to generate report.

Please do let me know for additional details required.

Regards,
Amarnath

**Comment by AmarnathN** [comment]
HI Team,

Can someone able to reproduce and verify the above mentioned error.

**Comment by ruzeynalov** [comment]
Hi guys, 

I can provide skeleton of the project in order to help you with reproducing this defect

https://github.com/ruzeynalov/cucumber-jvm-report-portal

**Comment by ruzeynalov** [comment]
My assumption that root of the problem is incompatibility between newer version of cucumber (2.xx) and gherkin plugin dependency (5.0.0) with gherkin plugin version mentioned in https://github.com/reportportal/agent-java-cucumber/blob/master/build.gradle#L29

**Comment by ruzeynalov** [comment]
Hi guys, 

any updates from your investigation? I would really love to use report portal with latest version of cucumber in my framework

**Comment by irshad413** [comment]
i know it's weird. I faced the same issue, i navigated to my maven repo and found that extension is missing in name "gherkin-2.12.2". I renamed it and added an extension as .jar and it solved the issue.

It's a frequent issue when u are getting ur dependencies from pom. Another way is you download gherkin-2.12.2.jar, gherkin-2.12.2-sources.jar and other required files from https://repo1.maven.org/maven2/info/cukes/gherkin/2.12.2/ and add them in your library.

Hope this helps. Cheers 👍

**Comment by ruzeynalov** [comment]
Hi @irshad413 

I use maven build tool so I would not consider an option to pack jar file along with my maven project. I believe that developers of report portal are responsible for reimplementing agent-java-cucumber with support for gherking 5.0.0 and cucumber 2.x, as stated in the comment here https://github.com/reportportal/agent-java-cucumber/issues/10#issuecomment-368917263

**Comment by celownick** [comment]
Hi, 
I've got the same problem. Cucumber 2.4.0 Gherkin 5.00 and above error appears. Any solutions?

**Comment by DEEPAKTIWARI2006** [comment]
seems like the issue is not resolved yet. I am using cucumber 3.0.2 and gherkin version 5.1.0.

**Comment by nsmorozov** [comment]
Having the same issue for cucumber 3.0.2. and gherkin 5.0.0

**Comment by cesarmirandaro** [comment]
same issue cucumber 2.3.1 and gherkin 5.0.0

**Comment by tcolombo08** [comment]
Hi guys, same issue here! Any plans on solving this?

**Comment by cvarshn** [comment]
use cucumber 2.4.0 and gherkin 5.1.0 it is working fine.

**Comment by AlexanderVegazo** [comment]
Hi guys, after a long troubleshooting i solved it. Please consider the checked answer on this stack overflow post:
https://stackoverflow.com/questions/36771066/java-lang-noclassdeffounderror-exception-while-running-cucumber-test-using-junit

I hope help you.

**Comment by kirylKarpau** [comment]
Faced with same issue today. @avarabyeu , @pbortnik Do you have a plan when it will be fixed? Do you know any workaround?

**Comment by cvarshn** [comment]
Hey,

This issue came due to incompatible combination of selenium and gherkin
dependency. Try changing gherkin dependency version this issue will be
resolved.

Thanks
Chandan

**Comment by Shrutirishiraj** [comment]
> use cucumber 2.4.0 and gherkin 5.1.0 it is working fine.

yes its working for me toooooooooo

**Comment by pikomdas** [comment]
update dependencies in POM.XML as mentioned below. It should work.

`<dependencies>
	
	<dependency>
		<groupId>junit</groupId>
		<artifactId>junit</artifactId>
		<version>${junit.version}</version>
		<scope>test</scope>
	</dependency>
	
	<dependency>
		<groupId>info.cukes</groupId>
		<artifactId>cucumber-junit</artifactId>
		<version>${cucumber-junit.version}</version>
		<scope>test</scope>
	</dependency>
	
	<dependency>
		<groupId>info.cukes</groupId>
		<artifactId>cucumber-java8</artifactId>
		<version>${cucumber-java8.version}</version>
		<scope>provided</scope>
	</dependency>
	
	<dependency>
		<groupId>info.cukes</groupId>
		<artifactId>cucumber-core</artifactId>
		<version>${cucumber-core.version}</version>
	</dependency>
	
	<dependency>
		<groupId>org.seleniumhq.selenium</groupId>
		<artifactId>selenium-java</artifactId>
		<version>${selenium.version}</version>
	</dependency>
	
	<dependency>
		<groupId>info.cukes</groupId>
		<artifactId>gherkin</artifactId>
		<version>${gherkin.version}</version>
		<scope>provided</scope>
	</dependency>
	<dependency>
		<groupId>info.cukes</groupId>
		<artifactId>cucumber-jvm-deps</artifactId>
		<version>${cucumber-jvm-deps.version}</version>
	</dependency>
	
	<dependency>
		<groupId>net.masterthought</groupId>
		<artifactId>cucumber-reporting</artifactId>
		<version>${cucumber-reporting.version}</version>
	</dependency>
    <dependency>
		<groupId>com.vimalselvam</groupId>
		<artifactId>cucumber-extentsreport</artifactId>
		<version>${cucumber-extentsreport.version}</version>
	</dependency>
	<dependency>
		<groupId>com.aventstack</groupId>
		<artifactId>extentreports</artifactId>
		<version>${extentreports.version}</version>
	</dependency>
	
	<dependency>
		<groupId>org.apache.logging.log4j</groupId>
		<artifactId>log4j-core</artifactId>
		<version>2.11.1</version>
	</dependency>
	
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.11.1</version>
		</dependency>
    
	<dependency>
		<groupId>com.googlecode.json-simple</groupId>
		<artifactId>json-simple</artifactId>
		<version>1.1.1</version>
	</dependency>
	
	<dependency>
		<groupId>org.slf4j</groupId>
		<artifactId>slf4j-api</artifactId>
		<version>1.7.7</version>
	</dependency>
</dependencies>`

**Comment by filland** [comment]
Better late than never...
To avoid problems with versions mess there is a compatibility matrix - https://github.com/reportportal/agent-java-cucumber/tree/readme-change#compatibility-matrix-for-cucumber-agents

This table might help you to chose the right versions of all libs.

**Comment by saravanan7** [comment]
Hello All,
This is simple but took time for me to find. Just change your scope in maven dependency to compile or comment the scope.
<dependency>
            <groupId>info.cukes</groupId>
            <artifactId>gherkin</artifactId>
            <version>2.12.2</version>
            <scope>compile</scope>
        </dependency>

OR

<dependency>
            <groupId>info.cukes</groupId>
            <artifactId>gherkin</artifactId>
            <version>2.12.2</version>
        </dependency>

**Comment by filland** [comment]
@saravanan7 
https://github.com/reportportal/agent-java-cucumber#compatibility-matrix-for-cucumber-agents

**Comment by marinataranchuk** [comment]
@filland  could you please help me clarify this issue?
According to compatibility matrix provided, recent Cucumber should work with Gherkin up to 5.1.0 and Cucumber agent 4.0.0
However, in the cucumber agent 4.0.0 (and in the recent code as well - https://github.com/reportportal/agent-java-cucumber/blob/master/src/main/java/com/epam/reportportal/cucumber/AbstractReporter.java ) I can see the following import:
```
import gherkin.formatter.Formatter;
import gherkin.formatter.Reporter;
import gherkin.formatter.model.*;
```
I can see that such package 'gherkin.formatter' is only present in Gherkin up to 2.12.2 , and starting from Gherkin 3.2.0 package structure is changed.
Therefore, it seems that to use ReportPortal Cucumber agent, I have to use Gherkin 2.12.2 and Cucumber 1.2.5 accordingly.

I have tried different combinations of Gherkin 3.2.0-5.1.0 and cucumber agent 4.0.0+, as suggested in the compatibility table, but the titulary 'NoClassDefFoundError' is always thrown, and the imports in the agent-java-cucumber listed above seem to be the cause.

**Comment by jonasleao** [comment]
seems like the issue is not resolved yet. I am using cucumber 4.2.6 and gherkin version 5.1.0.
cucumber agent 4.0.0 and I also get the error: java.lang.NoClassDefFoundError: gherkin/formatter/Formatter

**Comment by VladimirDrumea** [comment]
> seems like the issue is not resolved yet. I am using cucumber 4.2.6 and gherkin version 5.1.0.
> cucumber agent 4.0.0 and I also get the error: java.lang.NoClassDefFoundError: gherkin/formatter/Formatter

The asme for me :(

**Comment by mmehsan** [comment]
I'm using cucumber-java 4.3.1 and gherkins 5.1.0, when I execute it using maven in IntelliJ then I'm able to execute it successfully but when I try to execute any single feature file directly then I get `java.lang.ClassNotFoundException: gherkin.formatter.Formatter`

`  <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>4.3.1</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.25</version>
            <scope>test</scope>
        </dependency>

        
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.14.3</version>
            <scope>test</scope>
        </dependency>

        
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-testng</artifactId>
            <version>4.3.1</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-jvm-deps</artifactId>
            <version>1.0.6</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>gherkin-jvm-deps</artifactId>
            <version>1.0.4</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>gherkin</artifactId>
            <version>5.1.0</version>
        </dependency>
`

**Comment by tukaram57** [comment]
Was facing same issue. 
If we have proper combination of Intellij and cucumber plugin version, this issue will be resolved by putting feature files in test resource's features directory. 
With above step, its all good now.

**Comment by shahnawazm786** [comment]
I am using latest one, getting following error.
C:\jdk1.8\bin\java.exe -ea -DnodeNamesHandler=org.jetbrains.plugins.cucumber.java.run.CucumberTestTreeNodeManager -Didea.test.cyclic.buffer.size=1048576 -javaagent:C:\IntelliJ_IDEA\lib\idea_rt.jar=55689:C:\IntelliJ_IDEA\bin -Dfile.encoding=UTF-8 -classpath C:\IntelliJ_IDEA\lib\idea_rt.jar;C:\IntelliJ_IDEA\plugins\junit\lib\junit5-rt.jar;C:\IntelliJ_IDEA\plugins\junit\lib\junit-rt.jar;C:\jdk1.8\jre\lib\charsets.jar;C:\jdk1.8\jre\lib\deploy.jar;C:\jdk1.8\jre\lib\ext\access-bridge-64.jar;C:\jdk1.8\jre\lib\ext\cldrdata.jar;C:\jdk1.8\jre\lib\ext\dnsns.jar;C:\jdk1.8\jre\lib\ext\jaccess.jar;C:\jdk1.8\jre\lib\ext\jfxrt.jar;C:\jdk1.8\jre\lib\ext\localedata.jar;C:\jdk1.8\jre\lib\ext\nashorn.jar;C:\jdk1.8\jre\lib\ext\sunec.jar;C:\jdk1.8\jre\lib\ext\sunjce_provider.jar;C:\jdk1.8\jre\lib\ext\sunmscapi.jar;C:\jdk1.8\jre\lib\ext\sunpkcs11.jar;C:\jdk1.8\jre\lib\ext\zipfs.jar;C:\jdk1.8\jre\lib\javaws.jar;C:\jdk1.8\jre\lib\jce.jar;C:\jdk1.8\jre\lib\jfr.jar;C:\jdk1.8\jre\lib\jfxswt.jar;C:\jdk1.8\jre\lib\jsse.jar;C:\jdk1.8\jre\lib\management-agent.jar;C:\jdk1.8\jre\lib\plugin.jar;C:\jdk1.8\jre\lib\resources.jar;C:\jdk1.8\jre\lib\rt.jar;F:\Cucumber_BDD\BDDCucumber_Pavan\target\test-classes;C:\Users\ADMIN\.m2\repository\io\cucumber\cucumber-core\6.10.3\cucumber-core-6.10.3.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\cucumber-gherkin\6.10.3\cucumber-gherkin-6.10.3.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\cucumber-gherkin-messages\6.10.3\cucumber-gherkin-messages-6.10.3.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\messages\15.0.0\messages-15.0.0.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\tag-expressions\3.0.1\tag-expressions-3.0.1.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\cucumber-expressions\10.3.0\cucumber-expressions-10.3.0.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\datatable\3.5.0\datatable-3.5.0.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\cucumber-plugin\6.10.3\cucumber-plugin-6.10.3.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\docstring\6.10.3\docstring-6.10.3.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\html-formatter\13.0.0\html-formatter-13.0.0.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\create-meta\4.0.0\create-meta-4.0.0.jar;C:\Users\ADMIN\.m2\repository\org\apiguardian\apiguardian-api\1.1.1\apiguardian-api-1.1.1.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\cucumber-java\6.10.3\cucumber-java-6.10.3.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\cucumber-junit\6.10.3\cucumber-junit-6.10.3.jar;C:\Users\ADMIN\.m2\repository\org\seleniumhq\selenium\selenium-java\3.141.59\selenium-java-3.141.59.jar;C:\Users\ADMIN\.m2\repository\org\seleniumhq\selenium\selenium-api\3.141.59\selenium-api-3.141.59.jar;C:\Users\ADMIN\.m2\repository\org\seleniumhq\selenium\selenium-chrome-driver\3.141.59\selenium-chrome-driver-3.141.59.jar;C:\Users\ADMIN\.m2\repository\org\seleniumhq\selenium\selenium-edge-driver\3.141.59\selenium-edge-driver-3.141.59.jar;C:\Users\ADMIN\.m2\repository\org\seleniumhq\selenium\selenium-firefox-driver\3.141.59\selenium-firefox-driver-3.141.59.jar;C:\Users\ADMIN\.m2\repository\org\seleniumhq\selenium\selenium-ie-driver\3.141.59\selenium-ie-driver-3.141.59.jar;C:\Users\ADMIN\.m2\repository\org\seleniumhq\selenium\selenium-opera-driver\3.141.59\selenium-opera-driver-3.141.59.jar;C:\Users\ADMIN\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\3.141.59\selenium-remote-driver-3.141.59.jar;C:\Users\ADMIN\.m2\repository\org\seleniumhq\selenium\selenium-safari-driver\3.141.59\selenium-safari-driver-3.141.59.jar;C:\Users\ADMIN\.m2\repository\org\seleniumhq\selenium\selenium-support\3.141.59\selenium-support-3.141.59.jar;C:\Users\ADMIN\.m2\repository\net\bytebuddy\byte-buddy\1.8.15\byte-buddy-1.8.15.jar;C:\Users\ADMIN\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;C:\Users\ADMIN\.m2\repository\com\google\guava\guava\25.0-jre\guava-25.0-jre.jar;C:\Users\ADMIN\.m2\repository\com\google\code\findbugs\jsr305\1.3.9\jsr305-1.3.9.jar;C:\Users\ADMIN\.m2\repository\org\checkerframework\checker-compat-qual\2.0.0\checker-compat-qual-2.0.0.jar;C:\Users\ADMIN\.m2\repository\com\google\errorprone\error_prone_annotations\2.1.3\error_prone_annotations-2.1.3.jar;C:\Users\ADMIN\.m2\repository\com\google\j2objc\j2objc-annotations\1.1\j2objc-annotations-1.1.jar;C:\Users\ADMIN\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.14\animal-sniffer-annotations-1.14.jar;C:\Users\ADMIN\.m2\repository\com\squareup\okhttp3\okhttp\3.11.0\okhttp-3.11.0.jar;C:\Users\ADMIN\.m2\repository\com\squareup\okio\okio\1.14.0\okio-1.14.0.jar;C:\Users\ADMIN\.m2\repository\net\masterthought\cucumber-reporting\4.7.0\cucumber-reporting-4.7.0.jar;C:\Users\ADMIN\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.9.8\jackson-databind-2.9.8.jar;C:\Users\ADMIN\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.9.0\jackson-annotations-2.9.0.jar;C:\Users\ADMIN\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.9.8\jackson-core-2.9.8.jar;C:\Users\ADMIN\.m2\repository\org\apache\velocity\velocity\1.7\velocity-1.7.jar;C:\Users\ADMIN\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;C:\Users\ADMIN\.m2\repository\commons-lang\commons-lang\2.4\commons-lang-2.4.jar;C:\Users\ADMIN\.m2\repository\velocity-tools\velocity-tools\1.4\velocity-tools-1.4.jar;C:\Users\ADMIN\.m2\repository\joda-time\joda-time\2.10.1\joda-time-2.10.1.jar;C:\Users\ADMIN\.m2\repository\org\apache\commons\commons-lang3\3.8.1\commons-lang3-3.8.1.jar;C:\Users\ADMIN\.m2\repository\commons-io\commons-io\2.6\commons-io-2.6.jar;C:\Users\ADMIN\.m2\repository\org\codehaus\plexus\plexus-utils\3.1.1\plexus-utils-3.1.1.jar;C:\Users\ADMIN\.m2\repository\org\jsoup\jsoup\1.11.3\jsoup-1.11.3.jar;C:\Users\ADMIN\.m2\repository\com\googlecode\owasp-java-html-sanitizer\owasp-java-html-sanitizer\20190325.1\owasp-java-html-sanitizer-20190325.1.jar;C:\Users\ADMIN\.m2\repository\commons-configuration\commons-configuration\1.10\commons-configuration-1.10.jar;C:\Users\ADMIN\.m2\repository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;C:\Users\ADMIN\.m2\repository\org\hamcrest\hamcrest-core\2.2\hamcrest-core-2.2.jar;C:\Users\ADMIN\.m2\repository\org\hamcrest\hamcrest\2.2\hamcrest-2.2.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\gherkin\18.1.0\gherkin-18.1.0.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\cucumber-html\0.2.7\cucumber-html-0.2.7.jar;C:\Users\ADMIN\.m2\repository\net\sourceforge\cobertura\cobertura\2.1.1\cobertura-2.1.1.jar;C:\Users\ADMIN\.m2\repository\org\ow2\asm\asm\5.0.1\asm-5.0.1.jar;C:\Users\ADMIN\.m2\repository\org\ow2\asm\asm-tree\5.0.1\asm-tree-5.0.1.jar;C:\Users\ADMIN\.m2\repository\org\ow2\asm\asm-commons\5.0.1\asm-commons-5.0.1.jar;C:\Users\ADMIN\.m2\repository\org\ow2\asm\asm-util\5.0.1\asm-util-5.0.1.jar;C:\Users\ADMIN\.m2\repository\org\ow2\asm\asm-analysis\5.0.1\asm-analysis-5.0.1.jar;C:\Users\ADMIN\.m2\repository\oro\oro\2.0.8\oro-2.0.8.jar;C:\Users\ADMIN\.m2\repository\jaxen\jaxen\1.1.4\jaxen-1.1.4.jar;C:\Users\ADMIN\.m2\repository\org\apache\ant\ant\1.8.3\ant-1.8.3.jar;C:\Users\ADMIN\.m2\repository\org\apache\ant\ant-launcher\1.8.3\ant-launcher-1.8.3.jar;C:\Users\ADMIN\.m2\repository\org\apache\ant\ant-junit\1.8.3\ant-junit-1.8.3.jar;C:\Users\ADMIN\.m2\repository\org\mortbay\jetty\servlet-api-2.5\6.1.14\servlet-api-2.5-6.1.14.jar;C:\Users\ADMIN\.m2\repository\org\mortbay\jetty\jetty\6.1.14\jetty-6.1.14.jar;C:\Users\ADMIN\.m2\repository\org\mortbay\jetty\jetty-util\6.1.14\jetty-util-6.1.14.jar;C:\jdk1.8\lib\tools.jar;C:\Users\ADMIN\.m2\repository\org\slf4j\slf4j-api\1.7.5\slf4j-api-1.7.5.jar;C:\Users\ADMIN\.m2\repository\ch\qos\logback\logback-classic\1.0.13\logback-classic-1.0.13.jar;C:\Users\ADMIN\.m2\repository\ch\qos\logback\logback-core\1.0.13\logback-core-1.0.13.jar;C:\Users\ADMIN\.m2\repository\io\cucumber\cucumber-jvm-deps\1.0.6\cucumber-jvm-deps-1.0.6.jar;C:\Users\ADMIN\.m2\repository\junit\junit\4.13\junit-4.13.jar;C:\Users\ADMIN\.m2\repository\tech\grasshopper\extentreports-cucumber5-adapter\2.8.0\extentreports-cucumber5-adapter-2.8.0.jar;C:\Users\ADMIN\.m2\repository\com\aventstack\extentreports\5.0.6\extentreports-5.0.6.jar;C:\Users\ADMIN\.m2\repository\io\reactivex\rxjava3\rxjava\3.0.4\rxjava-3.0.4.jar;C:\Users\ADMIN\.m2\repository\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar;C:\Users\ADMIN\.m2\repository\org\freemarker\freemarker\2.3.30\freemarker-2.3.30.jar;C:\Users\ADMIN\.m2\repository\org\projectlombok\lombok\1.18.12\lombok-1.18.12.jar;C:\Users\ADMIN\.m2\repository\com\google\code\gson\gson\2.8.6\gson-2.8.6.jar;C:\Users\ADMIN\.m2\repository\com\aventstack\klov-reporter\5.0.6\klov-reporter-5.0.6.jar;C:\Users\ADMIN\.m2\repository\org\mongodb\bson\3.6.4\bson-3.6.4.jar;C:\Users\ADMIN\.m2\repository\org\apache\httpcomponents\httpclient\4.5.2\httpclient-4.5.2.jar;C:\Users\ADMIN\.m2\repository\org\apache\httpcomponents\httpcore\4.4.4\httpcore-4.4.4.jar;C:\Users\ADMIN\.m2\repository\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\ADMIN\.m2\repository\org\apache\httpcomponents\httpmime\4.5.2\httpmime-4.5.2.jar;C:\Users\ADMIN\.m2\repository\tech\grasshopper\extent-pdf-report\1.7.0\extent-pdf-report-1.7.0.jar;C:\Users\ADMIN\.m2\repository\tech\grasshopper\cucumber-pdf-report\2.2.0\cucumber-pdf-report-2.2.0.jar;C:\Users\ADMIN\.m2\repository\org\apache\pdfbox\pdfbox\2.0.22\pdfbox-2.0.22.jar;C:\Users\ADMIN\.m2\repository\org\apache\pdfbox\fontbox\2.0.22\fontbox-2.0.22.jar;C:\Users\ADMIN\.m2\repository\org\knowm\xchart\xchart\3.8.0\xchart-3.8.0.jar;C:\Users\ADMIN\.m2\repository\de\erichseifert\vectorgraphics2d\VectorGraphics2D\0.13\VectorGraphics2D-0.13.jar;C:\Users\ADMIN\.m2\repository\de\rototor\pdfbox\graphics2d\0.30\graphics2d-0.30.jar;C:\Users\ADMIN\.m2\repository\com\madgag\animated-gif-lib\1.4\animated-gif-lib-1.4.jar;C:\Users\ADMIN\.m2\repository\org\yaml\snakeyaml\1.28\snakeyaml-1.28.jar;C:\Users\ADMIN\.m2\repository\tech\grasshopper\table-layout\1.2.0\table-layout-1.2.0.jar;C:\Users\ADMIN\.m2\repository\org\mongodb\mongodb-driver\3.3.0\mongodb-driver-3.3.0.jar;C:\Users\ADMIN\.m2\repository\org\mongodb\mongodb-driver-core\3.3.0\mongodb-driver-core-3.3.0.jar;C:\Users\ADMIN\AppData\Roaming\JetBrains\IdeaIC2020.3\plugins\cucumber-java\lib\cucumber-jvmFormatter.jar com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit4 runners.TestRunner

io.cucumber.core.exception.CucumberException: java.lang.NoClassDefFoundError: io/cucumber/core/internal/gherkin/ast/Node

	at io.cucumber.core.plugin.PluginFactory.newInstance(PluginFactory.java:120)
	at io.cucumber.core.plugin.PluginFactory.instantiate(PluginFactory.java:99)
	at io.cucumber.core.plugin.PluginFactory.create(PluginFactory.java:63)
	at io.cucumber.core.plugin.Plugins.createPlugins(Plugins.java:32)
	at io.cucumber.core.plugin.Plugins.<init>(Plugins.java:25)
	at io.cucumber.junit.Cucumber.<init>(Cucumber.java:162)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.NoClassDefFoundError: io/cucumber/core/internal/gherkin/ast/Node
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter.<init>(ExtentCucumberAdapter.java:95)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.cucumber.core.plugin.PluginFactory.newInstance(PluginFactory.java:116)
	... 20 more
Caused by: java.lang.ClassNotFoundException: io.cucumber.core.internal.gherkin.ast.Node
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 26 more


Process finished with exit code -1

pom.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>BDDCucumber_Pavan</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-core</artifactId>
        <version>6.10.3</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>6.10.3</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>6.10.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.141.59</version>
        </dependency>
        <dependency>
            <groupId>net.masterthought</groupId>
            <artifactId>cucumber-reporting</artifactId>
            <version>4.7.0</version>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-core</artifactId>
            <version>2.2</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>gherkin</artifactId>
            <version>18.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-html</artifactId>
            <version>0.2.7</version>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.cobertura</groupId>
            <artifactId>cobertura</artifactId>
            <version>2.1.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-jvm-deps</artifactId>
            <version>1.0.6</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>tech.grasshopper</groupId>
            <artifactId>extentreports-cucumber5-adapter</artifactId>
            <version>2.8.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>







--------------------------
package runners;


import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;
import io.cucumber.junit.Cucumber;
@RunWith(Cucumber.class)
@CucumberOptions(
        features = "src/test/resources/Features",
        glue = "stepDefinitions",
        plugin = {"com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:"},
        dryRun = true,
        monochrome = true

)
public class TestRunner {
}

**Comment by HardNorth** [comment]
@shahnawazm786 we are Report Portal, and we have nothing to do with Extent Report.
